# Generated by Django 5.1.1 on 2024-09-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
