# Generated by Django 5.1.1 on 2024-09-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movie_upload_date_movie_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
