# Generated by Django 5.1.1 on 2024-11-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_watchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Tamil', max_length=50),
        ),
    ]
