# Generated by Django 5.1.1 on 2024-11-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_series_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='series_posters/'),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('release_year', models.PositiveIntegerField(default=2000)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='myapp.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('video_file', models.FileField(upload_to='episodes/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='myapp.season')),
            ],
        ),
    ]
