# Generated by Django 5.1.1 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_series_genre_series_poster_series_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='series/thumbnails/'),
        ),
    ]
