# Generated by Django 5.1.1 on 2024-11-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_series_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category'),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='Tamil', max_length=50),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='series_thumbnails/'),
        ),
    ]
