# Generated by Django 5.1.1 on 2024-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_episode_video_url_series_category_series_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
