# Generated by Django 5.1.1 on 2024-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_movie_poster_url_movie_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/default-profile'),
        ),
    ]
