# Generated by Django 5.1.1 on 2025-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_update_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates_images/'),
        ),
        migrations.AddField(
            model_name='update',
            name='movie_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
