# Generated by Django 5.1.1 on 2026-01-17 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_broadcastemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='last_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stream_type', models.CharField(choices=[('movie', 'Movie'), ('episode', 'Episode')], max_length=10)),
                ('quality', models.CharField(help_text='Example: 480p, 720p, 1080p', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='streams/')),
                ('video_url', models.URLField(blank=True, help_text='CDN / Cloud storage URL', null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='myapp.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='myapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.stream'),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'stream')},
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['stream_id'], name='myapp_strea_stream__f8be9b_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['movie'], name='myapp_strea_movie_i_20ce21_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['episode'], name='myapp_strea_episode_f34e70_idx'),
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='watched_on',
        ),
    ]
